export default {
  'off': {},
  'co-909': {
    numSteps: 16,
    playerInstruments: [{
      name: 'bass drum',
      low: 'sounds/co-909/909-BD-low.wav',
      high: 'sounds/co-909/909-BD-high.wav',
    }, {
      name: 'snare drum',
      low: 'sounds/co-909/909-SD-low.wav',
      'high': 'sounds/co-909/909-SD-high.wav',
    }, {
      name: 'hi hat',
      low: 'sounds/co-909/909-HH-closed.wav',
      high: 'sounds/co-909/909-HH-open.wav',
    }, {
      name: 'mid tom',
      low: 'sounds/co-909/909-MT-low.wav',
      high: 'sounds/co-909/909-MT-high.wav',
    }, {
      name: 'rim shot / hand clap',
      low: 'sounds/co-909/909-PC-rimshot.wav',
      high: 'sounds/co-909/909-PC-clap.wav',
    }, {
      name: 'high tom',
      low: 'sounds/co-909/909-HT-low.wav',
      high: 'sounds/co-909/909-HT-high.wav',
    }, {
      name: 'low tom',
      low: 'sounds/co-909/909-LT-low.wav',
      high: 'sounds/co-909/909-LT-high.wav',
    }, {
      name: 'cymbal',
      low: 'sounds/co-909/909-CY-ride.wav',
      high: 'sounds/co-909/909-CY-crash.wav',
    }, ],
    barrelInstruments: [{
      name: 'bass drum',
      low: 'sounds/co-909/909-BD-low.wav',
      high: 'sounds/co-909/909-BD-high.wav',
    }, {
      name: 'snare drum',
      low: 'sounds/co-909/909-SD-low.wav',
      'high': 'sounds/co-909/909-SD-high.wav',
    }, {
      name: 'hi hat',
      low: 'sounds/co-909/909-HH-closed.wav',
      high: 'sounds/co-909/909-HH-open.wav',
    }, {
      name: 'mid tom',
      low: 'sounds/co-909/909-MT-low.wav',
      high: 'sounds/co-909/909-MT-high.wav',
    }, {
      name: 'rim shot / hand clap',
      low: 'sounds/co-909/909-PC-rimshot.wav',
      high: 'sounds/co-909/909-PC-clap.wav',
    }, {
      name: 'high tom',
      low: 'sounds/co-909/909-HT-low.wav',
      high: 'sounds/co-909/909-HT-high.wav',
    }, {
      name: 'low tom',
      low: 'sounds/co-909/909-LT-low.wav',
      high: 'sounds/co-909/909-LT-high.wav',
    }, {
      name: 'cymbal',
      low: 'sounds/co-909/909-CY-ride.wav',
      high: 'sounds/co-909/909-CY-crash.wav',
    }, ],
  },
  'collective-loops': {
    numSteps: 8,
    playerNotes: [{
      class: 'perc',
      buffer: 'sounds/collective-loops/perc-01.mp3',
      gain: 1,
    }, {
      class: 'perc',
      buffer: 'sounds/collective-loops/perc-02.mp3',
      gain: 1,
    }, {
      class: 'perc',
      buffer: 'sounds/collective-loops/perc-03.mp3',
      gain: 1
    }, {
      class: 'bass',
      buffer: 'sounds/collective-loops/bass-01.mp3',
      gain: 1
    }, {
      class: 'bass',
      buffer: 'sounds/collective-loops/bass-02.mp3',
      gain: 1
    }, {
      class: 'bass',
      buffer: 'sounds/collective-loops/bass-03.mp3',
      gain: 0.8,
    }, {
      class: 'bass',
      buffer: 'sounds/collective-loops/bass-04.mp3',
      gain: 0.8,
    }, {
      class: 'bass',
      buffer: 'sounds/collective-loops/bass-05.mp3',
      gain: 0.8,
    }, {
      class: 'bass',
      buffer: 'sounds/collective-loops/bass-06.mp3',
      gain: 0.8,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-01.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-02.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-03.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-04.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-05.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-06.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-07.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-08.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-09.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-10.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-11.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-12.mp3',
      gain: 0.3,
    }, ],
    barrelNotes: [{
      class: 'perc',
      buffer: 'sounds/collective-loops/perc-01.mp3',
      gain: 1,
    }, {
      class: 'perc',
      buffer: 'sounds/collective-loops/perc-02.mp3',
      gain: 1,
    }, {
      class: 'perc',
      buffer: 'sounds/collective-loops/perc-03.mp3',
      gain: 0.8,
    }, {
      class: 'bass',
      buffer: 'sounds/collective-loops/bass-01.mp3',
      gain: 0.8,
    }, {
      class: 'bass',
      buffer: 'sounds/collective-loops/bass-02.mp3',
      gain: 0.8,
    }, {
      class: 'bass',
      buffer: 'sounds/collective-loops/bass-03.mp3',
      gain: 0.8,
    }, {
      class: 'bass',
      buffer: 'sounds/collective-loops/bass-04.mp3',
      gain: 1,
    }, {
      class: 'bass',
      buffer: 'sounds/collective-loops/bass-05.mp3',
      gain: 1
    }, {
      class: 'bass',
      buffer: 'sounds/collective-loops/bass-06.mp3',
      gain: 1
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-01.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-02.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-03.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-04.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-05.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-06.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-07.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-08.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-09.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-10.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-11.mp3',
      gain: 0.3,
    }, {
      class: 'melody',
      buffer: 'sounds/collective-loops/marimba-12.mp3',
      gain: 0.3,
    }, ],
  },
};
